services:
  db:
    image: docker.io/postgis/postgis:latest
    environment:
      POSTGRES_USER: atenea
      POSTGRES_PASSWORD: atenea
      POSTGRES_DB: atenea
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    volumes:
      - ./:/app
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
